#!/bin/bash

if [  $# -le 1 ]; then 
    echo "Usage: pronounce [language] [word]"
	exit 1
fi 

lang=$1
word=$2

filepath=$(curl -s https://forvo.com/search/$word/$lang | grep -m 1 'play_' | cut -d',' -f2)

curl -s https://forvo.com/player-mp3Handler.php?path=$filepath | mpv - 
