#!/bin/bash

word=$1
lang="#ja"

filepath="$(curl -s https://forvo.com/search/$word/$lang | grep -m 1 'play_' | cut -d',' -f2 | sed "s/'//g")"

curl -s https://forvo.com/player-mp3Handler.php?path=$filepath | cvlc --play-and-exit - 
