#!/bin/bash

url="http://link.springer.com/download/epub/10.1007/"
bookpath="epubbooks"
> not_foundepub # create empty file in case script runs multiple times
mkdir -p $bookpath

while read p; do
    curl -sL $p > tmp_file
    isbn=$(cut -d "=" -f3 <<< $p)
    title=$(grep -m1 "<h1>" tmp_file | sed -e 's/<h1>//g' -e 's_</h1>__g' | tr -d ' ')

    # springer book doesnt organize all books by ISBN
    if curl -L --output /dev/null --silent --head --fail "$url$isbn.epub"
    then
        curl -L "$url$isbn.epub" --output "$bookpath/$title.epub"
    else
        download_url=$(grep "class=\"c-button c-button__icon-right test-bookepub-link\"" \
            tmp_file | grep -Eo -m 1 'href="[^\"]+"' | sed -e s/href=//g -e s/\"//g -e s_/download/epub/10.1007%2F__g)

        if curl -L --output /dev/null --silent --head --fail "$url$download_url"
        then
            curl -L "$url$download_url" --output "$bookpath/$title.epub"
        else
            printf "Did not find epub version of '$title'\n\n"
            echo $title >> not_foundepub
        fi
    fi

done <links.txt
