#!/bin/bash

for username in $(cat users.txt | sed -e 's/.*@\(.*\)?????.*/\1/'); do
   password=$(echo $username | sha256sum | base64 | head -c 32)

   echo "$password $username" >> accounts.txt
done
